// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1BMy7zZDjDQEWxgj-MBLPf_ipv-lsDpY',
    appId: '1:320817533981:web:d60db2fd3f04a059fd62f4',
    messagingSenderId: '320817533981',
    projectId: 'screen-sharing-demo',
    authDomain: 'screen-sharing-demo.firebaseapp.com',
    storageBucket: 'screen-sharing-demo.appspot.com',
    measurementId: 'G-NYVD00M5L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHBluxvFM2yMQKdzCEczv0sLMhds2wekg',
    appId: '1:320817533981:android:e5f9322909533d20fd62f4',
    messagingSenderId: '320817533981',
    projectId: 'screen-sharing-demo',
    storageBucket: 'screen-sharing-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNYeUfFEoX0SzGs57MEyLN7DotVISJltE',
    appId: '1:320817533981:ios:ab14d576e07d83aefd62f4',
    messagingSenderId: '320817533981',
    projectId: 'screen-sharing-demo',
    storageBucket: 'screen-sharing-demo.appspot.com',
    iosBundleId: 'com.example.screenSharingFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNYeUfFEoX0SzGs57MEyLN7DotVISJltE',
    appId: '1:320817533981:ios:1c60c6ba72c45339fd62f4',
    messagingSenderId: '320817533981',
    projectId: 'screen-sharing-demo',
    storageBucket: 'screen-sharing-demo.appspot.com',
    iosBundleId: 'com.example.screenSharingFix.RunnerTests',
  );
}
